mybatis:
  typeAliasesPackage: com.yu.pojo
  mapperLocations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    username: root
    password: 666666
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver

#logging:
#  level:
#    com.yu: debug