server:
  port: 8080
  servlet:
    context-path: /community

mybatis:
  typeAliasesPackage: com.yu.pojo
  mapperLocations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

spring:
  datasource:
    username: root
    password: 666666
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mail:
    host: smtp.163.com
    port: 465
    username: h578960@163.com
    password: FAGFGLYQKRNCOIXJ
    protocol: smtps
    properties:
      mail.smtp.ssl.enable: true
  thymeleaf:
    cache: false
  redis:
    database: 11
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  elasticsearch:
    uris: 127.0.0.1:9200
    username: yu
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    scheduling:
      pool:
        size: 5
  quartz:
    job-store-type: JDBC
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

community:
  path:
    domain: http://localhost:8080
    upload: d:/javaweb/data/upload

wk:
  image:
    command: d:/wkhtmltopdf/bin/wkhtmltoimage
    storage: d:/javaweb/wk-images

qiniu:
  key:
    access: ucnILTAGzlUqsAjD-fsS9SO4eq0ydekBo9hgSknh
    secret: Z0D1jk4wzhrT7m69U460r-_uI1rI275zexMsGS4l
  bucket:
    header:
      name: communityheaderyu
      url: http://rcp2x4fzq.bkt.clouddn.com
    share:
      name: communityshareyu
      url: http://rcp2xxv9r.bkt.clouddn.com

caffeine:
  posts:
    max-size: 15
    expire-seconds: 180
